id: PBC36540D
initial_creation_type: input
source_metadata:
  Title: Catuṣpariṣat sūtram
  Editor: Gippert, J. and Kupfer
  Publisher: Titus Version
  Place of Publication: Frankfurt
  Year: '2000'
  Catuṣpariṣat sūtram:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:00:33.403160'
last_modified_at: '2022-03-08T16:00:33.403170'
